# k8s/version1/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-version1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-version1
  template:
    metadata:
      labels:
        app: my-app-version1
    spec:
      containers:
      - name: my-app-version1
        image: my-docker-repo/version1
