# k8s/version3/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-version3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-version3
  template:
    metadata:
      labels:
        app: my-app-version3
    spec:
      containers:
      - name: my-app-version3
        image: my-docker-repo/version3
